name: Build and Publish multi-arch Containers

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "20 02 * * *"
  workflow_dispatch:  # Enable manual triggering

permissions:
  packages: write

jobs:
  build-multiarch:
    name: Build and push image
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [amd64, arm64] # amd64 = x86_64, arm64 = aarch64

    env:
      IMAGE_NAME: fedora-silverblue-image
      IMAGE_TAGS: latest ${{ github.sha }}
      REGISTRY_URL: ghcr.io/${{ github.repository_owner }}
      REGISTRY_USER: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ github.token }}

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main

      - name:  Download latest package list from the repositories
        run: sudo apt update

      - name: Install Packages
        run: sudo apt install -y buildah podman qemu-user-static

      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}-${{ matrix.arch }}
          tags: ${{ env.IMAGE_TAGS }}
          containerfiles: |
            ./Containerfile
          platforms: linux/${{ matrix.arch }}

      - name: Push Image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE_NAME }}-${{ matrix.arch }}
          tags: ${{ env.IMAGE_TAGS }}
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Set built image tags
        id: set-tags
        run: echo "image_tags=${{ env.IMAGE_NAME }}-${{ matrix.arch }}:${{ github.sha }}" >> $GITHUB_OUTPUT
